[build]
  functions = "netlify/functions"
  publish = "."
  command = "npm install"

[env]
  [env.production]
    SHOP_EMAIL = "mt1479233@gmail.com"
    APP_PASSWORD = "drykneiokjyrvudm"
    MONGODB_URI = "mongodb+srv://mt1479233_db_user:minhtran055@cluster0.qoy22yq.mongodb.net/thaovy_store?retryWrites=true&w=majority"
    AUTH_SECRET = "your-secret-key-change-this"
